set_property IOSTANDARD SSTL135 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[0]}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD SSTL135} [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property INTERNAL_VREF 0.675 [get_iobanks 34]
set_property IOSTANDARD LVCMOS33 [get_ports clk_button]
set_property PACKAGE_PIN G15 [get_ports clk_button]
set_property PACKAGE_PIN E18 [get_ports {data_out[0]}]
set_property PACKAGE_PIN F13 [get_ports {data_out[1]}]
set_property PACKAGE_PIN E13 [get_ports {data_out[2]}]
set_property PACKAGE_PIN H15 [get_ports {data_out[3]}]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD SSTL135} [get_ports {data_in[0]}]
set_property PACKAGE_PIN G18 [get_ports {data_in[2]}]
set_property PACKAGE_PIN M5 [get_ports {data_in[3]}]

set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]



set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN K16 [get_ports reset]
set_property PACKAGE_PIN H18 [get_ports {data_in[1]}]
